version: '3.7'

services:

  api_server:
    build:
        context: ./api_backend_server
        dockerfile: Dockerfile
    depends_on:
        - mongo
    image: api_server:latest
    ports: 
        - "80:5000"
    links: 
        - mongo
    environment:
        SECRET_KEY: ${SECRET_KEY}
        APISERVERPWD: ${APISERVERPWD}
        APISERVERUSR: ${APISERVERUSR}
        SENDGRID_API_KEY: ${SENDGRID_API_KEY}
        SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}

  mongo:
    build:
        context: ./mongo_db
        dockerfile: Dockerfile
    image: mongo_db:latest
    restart: always
    volumes:
        - type: bind
          source: ./mongo_db/data/db
          target: /data/db
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOADMINUSR}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOADMINPWD}
        MONGO_INITDB_DATABASE: ${MONGOINITDBDATABASE}
        ME_CONFIG_MONGODB_PORT: ${MECONFIGMONGODBPORT}
        APISERVERUSR: ${APISERVERUSR}
        APISERVERPWD: ${APISERVERPWD}
  
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
        - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOADMINUSR}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOADMINPWD}
        ME_CONFIG_MONGODB_PORT: ${MECONFIGMONGODBPORT}
        ME_CONFIG_MONGODB_SERVER: mongo